spring:
  application:
    name: catcat
  profiles:
    active: dev
    # active: prod
  cache: # 缓存配置
    type: redis
    redis:
      time-to-live: 1800000  # 缓存过期时间缩短到30分钟，减少内存占用
      cache-null-values: false
    caffeine:
      maximum-size: 500 # 缓存最大容量 500
      spec: 3 # 缓存过期时间 3分钟
    # rabbitmq:
    #   host: localhost
    #   port: 5672
    #   username: guest
    #   password: guest
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      password: 
      # Redis连接池配置
      lettuce:
        pool:
          max-active: 4  # 最大连接数
          max-idle: 2    # 最大空闲连接数
          min-idle: 1    # 最小空闲连接数
          max-wait: 1000 # 连接等待时间
      # 其他优化配置
      timeout: 1000     # 连接超时时间
      client-type: lettuce  # 使用lettuce客户端，性能更好

# 布隆过滤器配置
bloom:
  filter:
    cat-like:
      capacity: 10000    # 预计元素数量
      error-rate: 0.01   # 误判率
      name: "cat:like:bloom"  # 过滤器名称
#       reset-cron: "3 * * * * ?"  # 重置时间

# 缓存监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: catcat
    cache:
      instrument: true
# 微信配置
wx:
  appId: wx59bda6b87d597cbf
  appSecret: ce16d796044d4cee0b965fcf227079ce

